#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"__all__": "00_utils.ipynb",
         "as_tensor": "00_utils.ipynb",
         "as_normalised_tensor": "00_utils.ipynb",
         "bgr2rgb": "00_utils.ipynb",
         "bgr2hsv": "00_utils.ipynb",
         "lapply": "00_utils.ipynb",
         "read_video": "01_io.ipynb",
         "read_all_frames": "01_io.ipynb",
         "read_specific_frames": "01_io.ipynb",
         "capture": "01_io.ipynb"}

modules = ["utils.py",
           "io.py"]

git_url = "https://github.com/rsomani95/videoutils/tree/master/"

def custom_doc_links(name): return None